# Deep Learning Models Training(CNN,CRNN)

This Notebook is used to train deep learning models to complete Music Genre Classification.
The training model includes:

-CNN (Convolutional Neural Network)
-CRNN (Convolutional Recurrent Neural Network)

The training data uses Mel Spectrogram obtained by preprocessing in advance, and evaluates the model performance in combination with 5-fold Cross Validation.
Finally, use the entire training set to retrain the best model and save the trained parameters for subsequent testing and model evaluation.

## 1 Import Libaraies
The following libraries are imported fordata processing,deep learning,cross validation and model evaluation.

In [3]:
import os
import numpy as np
import pandas as pd

import torch
import torch.nn as nn

from torch.optim import Adam
from torch.utils.data import DataLoader, Dataset, Subset

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import f1_score

from model import CNN, CRNN
from train import GTZANDdataset,cross_validation,BATCH_SIZE,LEARNING_RATE,EPOCHS,NUM_CLASSES,DEVICE,Mel_dir

## 2 Prepare Training Dataset
This part is intended to prepare the data which will be used for training the models.
Workflow:X_train.csv-->Read filenames-->y_train.csv-->Read corresponding genre labels-->Locate Mel Spectrogram (.npy)
      -->Load Mel Spectrogram-->Standardize-->Convert to Tensor
(Dataset preparation is implemented in train.py.This notebook directly imports GTZANDdataset.)

## 3 Training Configuration

Batch Size：The number of samples used for each update of parameters
    Batch Size = 32

Learning Rate：Adam Optimizer learning rate
    Learning Rate = 0.0005

Epoch：The number of training sets that the model has been completed
    Epoch = 50

Number of Classes：Genres in GTZAN dataset：10 Genres。
    Number of Classes = 10

Device：Autometically detect GPU
    if GPU is available：CUDA
    otherwise：CPU

In [4]:
from train import (
    BATCH_SIZE,
    LEARNING_RATE,
    EPOCHS,
    NUM_CLASSES,
    DEVICE,
    Mel_dir,
)

print(f"Batch Size: {BATCH_SIZE}")
print(f"Learning Rate: {LEARNING_RATE}")
print(f"Epochs: {EPOCHS}")
print(f"Device: {DEVICE}")

Batch Size: 32
Learning Rate: 0.0005
Epochs: 50
Device: cpu

## 4 Load Traing Data
Load the pre-generated training feature and label files, then construct the PyTorch dataset for model training.

In [5]:
# Load training CSV files
x_train = pd.read_csv("X_train.csv")
y_train = pd.read_csv("y_train.csv")

# Create dataset
train_dataset = GTZANDdataset(Mel_dir, x_train, y_train)

print("Dataset Information")
print("-" * 40)
print(f"Training samples : {len(train_dataset)}")

labels = [label for _, label in train_dataset.samples]
print(f"Number of classes: {len(set(labels))}")

sample, label = train_dataset[0]
print(f"Input shape      : {tuple(sample.shape)}")
print(f"Sample label     : {label.item()}")

Dataset Information
----------------------------------------
Training samples : 804
Number of classes: 10
Input shape      : (1, 128, 1292)
Sample label     : 0

## 5 Cross Validation Setup
In order to improve the stability and classification performance of model training,our project adopts：5-Fold Cross Validation
Workflow：Training Dataset-->Split into 5 Folds-->4 Folds Training-->1 Fold Validation-->Repeat 5 Times
The macro F1 score is used as an evaluation indicator because it gives equal attention to each music genre.

In [6]:
kf = StratifiedKFold(
    n_splits = 5, 
    shuffle = True, 
    random_state = 42
)
print("Cross Validation Configuration")
print("- Number of folds : 5")
print("- Split method    : StratifiedKFold")
print("- Shuffle         : True")
print("- Random state    : 42")

Cross Validation Configuration
- Number of folds : 5
- Split method    : StratifiedKFold
- Shuffle         : True
- Random state    : 42

## 6 Training Pipeline
This part introduces the training process of CNN and CRNN. CNN and CRNN use the same training process. ( In order to better compare the differences between CNN and CRNN in dealing with music genres)
The training data adopts the preprocessed Mel Spectrogram, and the 5-Fold Cross Validation is used to evaluate the model performance. During the training process, the model learns the characteristic representation of different music genres by constantly updating the parameters, so as to improve the classification accuracy.

- Adam Optimizer is adopted to update network parameters because it combines momentum and adaptive learning rates, leading to faster and more stable convergence.

- Cross Entropy Loss is used for multi-class classification by measuring the difference between predicted probabilities and the true labels.
Five-fold Cross Validation evaluates the model's generalization performance. The average Macro F1 Score across all folds is used as the model evaluation criterion.

- Five-fold Cross Validation evaluates the model's generalization performance. The average Macro F1 Score across all folds is used as the model evaluation criterion.

## 7 CNN training

 ### 7.1 CNN training process
The CNN model is trained using five-fold stratified cross validation.  
- For each fold, the model is trained for 50 epochs using the Adam optimizer and CrossEntropyLoss.  
- The best Macro F1 score on the validation set is recorded for each fold, and the average Macro F1 across all folds is used to evaluate the model.

In [7]:
print("=" * 60)
print("CNN Training")
print("=" * 60)

cnn_avg_f1, cnn_fold_results = cross_validation(
    train_dataset,
    CNN
)

============================================================
CNN Training
============================================================
Fold 1
Epoch [1/50] Loss: 2.3308 Train Accuracy: 14.15% Validation Accuracy: 14.91% Macro F1:0.0808
Epoch [2/50] Loss: 2.2168 Train Accuracy: 18.97% Validation Accuracy: 21.12% Macro F1:0.1228
Epoch [3/50] Loss: 2.1629 Train Accuracy: 20.06% Validation Accuracy: 31.68% Macro F1:0.2338
Epoch [4/50] Loss: 2.0624 Train Accuracy: 23.33% Validation Accuracy: 36.02% Macro F1:0.2777
Epoch [5/50] Loss: 2.0263 Train Accuracy: 26.91% Validation Accuracy: 36.65% Macro F1:0.2560
Epoch [6/50] Loss: 1.9998 Train Accuracy: 26.44% Validation Accuracy: 36.65% Macro F1:0.2729
Epoch [7/50] Loss: 2.0159 Train Accuracy: 29.86% Validation Accuracy: 39.13% Macro F1:0.2958
Epoch [8/50] Loss: 1.9606 Train Accuracy: 30.64% Validation Accuracy: 39.13% Macro F1:0.2980
Epoch [9/50] Loss: 1.9566 Train Accuracy: 30.02% Validation Accuracy: 35.40% Macro F1:0.2532
Epoch [10/50] Loss: 1.9132 Train Accuracy: 30.95% Validation Accuracy: 40.37% Macro F1:0.3027
Epoch [11/50] Loss: 1.8948 Train Accuracy: 33.28% Validation Accuracy: 37.89% Macro F1:0.2879
Epoch [12/50] Loss: 1.8870 Train Accuracy: 33.59% Validation Accuracy: 40.37% Macro F1:0.3088
Epoch [13/50] Loss: 1.9051 Train Accuracy: 32.66% Validation Accuracy: 41.61% Macro F1:0.3412
Epoch [14/50] Loss: 1.8477 Train Accuracy: 34.99% Validation Accuracy: 40.37% Macro F1:0.3206
Epoch [15/50] Loss: 1.8080 Train Accuracy: 36.24% Validation Accuracy: 40.37% Macro F1:0.3362
Epoch [16/50] Loss: 1.8283 Train Accuracy: 33.59% Validation Accuracy: 42.24% Macro F1:0.3522
Epoch [17/50] Loss: 1.7936 Train Accuracy: 36.70% Validation Accuracy: 42.24% Macro F1:0.3600
Epoch [18/50] Loss: 1.7975 Train Accuracy: 33.75% Validation Accuracy: 39.75% Macro F1:0.3213
Epoch [19/50] Loss: 1.7557 Train Accuracy: 35.77% Validation Accuracy: 41.61% Macro F1:0.3320
Epoch [20/50] Loss: 1.8109 Train Accuracy: 36.39% Validation Accuracy: 43.48% Macro F1:0.3587
Epoch [21/50] Loss: 1.7414 Train Accuracy: 36.55% Validation Accuracy: 40.99% Macro F1:0.3203
Epoch [22/50] Loss: 1.7385 Train Accuracy: 36.39% Validation Accuracy: 40.99% Macro F1:0.3295
Epoch [23/50] Loss: 1.7423 Train Accuracy: 36.55% Validation Accuracy: 44.10% Macro F1:0.3790
Epoch [24/50] Loss: 1.7570 Train Accuracy: 36.55% Validation Accuracy: 42.86% Macro F1:0.3599
Epoch [25/50] Loss: 1.7155 Train Accuracy: 36.55% Validation Accuracy: 42.86% Macro F1:0.3480
Epoch [26/50] Loss: 1.7150 Train Accuracy: 38.41% Validation Accuracy: 44.10% Macro F1:0.3738
Epoch [27/50] Loss: 1.7013 Train Accuracy: 38.57% Validation Accuracy: 45.34% Macro F1:0.3961
Epoch [28/50] Loss: 1.7178 Train Accuracy: 37.17% Validation Accuracy: 44.72% Macro F1:0.3794
Epoch [29/50] Loss: 1.6725 Train Accuracy: 40.44% Validation Accuracy: 44.10% Macro F1:0.3837
Epoch [30/50] Loss: 1.6705 Train Accuracy: 35.61% Validation Accuracy: 44.72% Macro F1:0.3904
Epoch [31/50] Loss: 1.7033 Train Accuracy: 37.17% Validation Accuracy: 43.48% Macro F1:0.3793
Epoch [32/50] Loss: 1.6933 Train Accuracy: 38.57% Validation Accuracy: 43.48% Macro F1:0.3746
Epoch [33/50] Loss: 1.6201 Train Accuracy: 39.35% Validation Accuracy: 46.58% Macro F1:0.4197
Epoch [34/50] Loss: 1.6838 Train Accuracy: 37.95% Validation Accuracy: 47.20% Macro F1:0.4286
Epoch [35/50] Loss: 1.6649 Train Accuracy: 38.41% Validation Accuracy: 45.34% Macro F1:0.4137
Epoch [36/50] Loss: 1.6588 Train Accuracy: 37.33% Validation Accuracy: 47.20% Macro F1:0.4266
Epoch [37/50] Loss: 1.6860 Train Accuracy: 37.17% Validation Accuracy: 45.96% Macro F1:0.4063
Epoch [38/50] Loss: 1.6224 Train Accuracy: 42.15% Validation Accuracy: 44.10% Macro F1:0.3773
Epoch [39/50] Loss: 1.6664 Train Accuracy: 41.06% Validation Accuracy: 44.72% Macro F1:0.3986
Epoch [40/50] Loss: 1.6124 Train Accuracy: 41.68% Validation Accuracy: 47.20% Macro F1:0.4258
Epoch [41/50] Loss: 1.6144 Train Accuracy: 41.21% Validation Accuracy: 48.45% Macro F1:0.4489
Epoch [42/50] Loss: 1.5917 Train Accuracy: 41.06% Validation Accuracy: 48.45% Macro F1:0.4428
Epoch [43/50] Loss: 1.5506 Train Accuracy: 43.08% Validation Accuracy: 47.20% Macro F1:0.4263
Epoch [44/50] Loss: 1.5994 Train Accuracy: 40.90% Validation Accuracy: 49.07% Macro F1:0.4526
Epoch [45/50] Loss: 1.5942 Train Accuracy: 41.68% Validation Accuracy: 48.45% Macro F1:0.4383
Epoch [46/50] Loss: 1.6120 Train Accuracy: 40.90% Validation Accuracy: 48.45% Macro F1:0.4412
Epoch [47/50] Loss: 1.5819 Train Accuracy: 41.99% Validation Accuracy: 47.83% Macro F1:0.4230
Epoch [48/50] Loss: 1.5637 Train Accuracy: 43.86% Validation Accuracy: 50.93% Macro F1:0.4597
Epoch [49/50] Loss: 1.6140 Train Accuracy: 39.97% Validation Accuracy: 50.31% Macro F1:0.4583
Epoch [50/50] Loss: 1.5546 Train Accuracy: 41.52% Validation Accuracy: 50.31% Macro F1:0.4577
Fold 2
Epoch [1/50] Loss: 2.3311 Train Accuracy: 11.20% Validation Accuracy: 24.22% Macro F1:0.1208
Epoch [2/50] Loss: 2.2405 Train Accuracy: 16.64% Validation Accuracy: 32.30% Macro F1:0.2121
Epoch [3/50] Loss: 2.1679 Train Accuracy: 19.60% Validation Accuracy: 37.89% Macro F1:0.2736
Epoch [4/50] Loss: 2.0743 Train Accuracy: 24.57% Validation Accuracy: 36.02% Macro F1:0.2419
Epoch [5/50] Loss: 2.0612 Train Accuracy: 27.06% Validation Accuracy: 36.02% Macro F1:0.2470
Epoch [6/50] Loss: 2.0340 Train Accuracy: 25.19% Validation Accuracy: 34.16% Macro F1:0.2310
Epoch [7/50] Loss: 2.0285 Train Accuracy: 25.82% Validation Accuracy: 42.86% Macro F1:0.3315
Epoch [8/50] Loss: 1.9650 Train Accuracy: 30.33% Validation Accuracy: 44.72% Macro F1:0.3667
Epoch [9/50] Loss: 1.9593 Train Accuracy: 30.48% Validation Accuracy: 47.20% Macro F1:0.3847
Epoch [10/50] Loss: 1.9614 Train Accuracy: 24.88% Validation Accuracy: 40.37% Macro F1:0.3096
Epoch [11/50] Loss: 1.8778 Train Accuracy: 33.28% Validation Accuracy: 45.34% Macro F1:0.3616
Epoch [12/50] Loss: 1.9162 Train Accuracy: 30.48% Validation Accuracy: 45.34% Macro F1:0.3761
Epoch [13/50] Loss: 1.8765 Train Accuracy: 31.88% Validation Accuracy: 45.34% Macro F1:0.3845
Epoch [14/50] Loss: 1.8571 Train Accuracy: 34.68% Validation Accuracy: 47.20% Macro F1:0.4129
Epoch [15/50] Loss: 1.8211 Train Accuracy: 32.66% Validation Accuracy: 49.07% Macro F1:0.4108
Epoch [16/50] Loss: 1.8302 Train Accuracy: 34.68% Validation Accuracy: 45.96% Macro F1:0.3777
Epoch [17/50] Loss: 1.8222 Train Accuracy: 32.66% Validation Accuracy: 45.34% Macro F1:0.3744
Epoch [18/50] Loss: 1.7867 Train Accuracy: 34.53% Validation Accuracy: 50.93% Macro F1:0.4507
Epoch [19/50] Loss: 1.8056 Train Accuracy: 32.19% Validation Accuracy: 48.45% Macro F1:0.4190
Epoch [20/50] Loss: 1.7375 Train Accuracy: 36.39% Validation Accuracy: 46.58% Macro F1:0.3959
Epoch [21/50] Loss: 1.7179 Train Accuracy: 36.55% Validation Accuracy: 49.07% Macro F1:0.4256
Epoch [22/50] Loss: 1.7389 Train Accuracy: 36.86% Validation Accuracy: 45.96% Macro F1:0.4080
Epoch [23/50] Loss: 1.7196 Train Accuracy: 36.70% Validation Accuracy: 48.45% Macro F1:0.4157
Epoch [24/50] Loss: 1.7464 Train Accuracy: 34.37% Validation Accuracy: 49.07% Macro F1:0.4355
Epoch [25/50] Loss: 1.7079 Train Accuracy: 40.28% Validation Accuracy: 48.45% Macro F1:0.4371
Epoch [26/50] Loss: 1.7346 Train Accuracy: 36.24% Validation Accuracy: 46.58% Macro F1:0.4171
Epoch [27/50] Loss: 1.7114 Train Accuracy: 37.64% Validation Accuracy: 45.96% Macro F1:0.3940
Epoch [28/50] Loss: 1.7367 Train Accuracy: 35.77% Validation Accuracy: 48.45% Macro F1:0.4196
Epoch [29/50] Loss: 1.6938 Train Accuracy: 37.64% Validation Accuracy: 48.45% Macro F1:0.4251
Epoch [30/50] Loss: 1.7243 Train Accuracy: 36.24% Validation Accuracy: 48.45% Macro F1:0.4348
Epoch [31/50] Loss: 1.7331 Train Accuracy: 35.15% Validation Accuracy: 45.96% Macro F1:0.3938
Epoch [32/50] Loss: 1.6698 Train Accuracy: 39.66% Validation Accuracy: 47.83% Macro F1:0.4124
Epoch [33/50] Loss: 1.6917 Train Accuracy: 36.86% Validation Accuracy: 50.31% Macro F1:0.4603
Epoch [34/50] Loss: 1.6790 Train Accuracy: 39.19% Validation Accuracy: 50.93% Macro F1:0.4612
Epoch [35/50] Loss: 1.6894 Train Accuracy: 39.81% Validation Accuracy: 49.69% Macro F1:0.4399
Epoch [36/50] Loss: 1.6462 Train Accuracy: 39.19% Validation Accuracy: 47.20% Macro F1:0.4192
Epoch [37/50] Loss: 1.6329 Train Accuracy: 39.35% Validation Accuracy: 50.93% Macro F1:0.4666
Epoch [38/50] Loss: 1.6662 Train Accuracy: 39.66% Validation Accuracy: 50.31% Macro F1:0.4485
Epoch [39/50] Loss: 1.6376 Train Accuracy: 38.88% Validation Accuracy: 49.69% Macro F1:0.4412
Epoch [40/50] Loss: 1.6075 Train Accuracy: 41.06% Validation Accuracy: 50.93% Macro F1:0.4646
Epoch [41/50] Loss: 1.5797 Train Accuracy: 39.97% Validation Accuracy: 50.31% Macro F1:0.4530
Epoch [42/50] Loss: 1.6061 Train Accuracy: 41.06% Validation Accuracy: 49.69% Macro F1:0.4461
Epoch [43/50] Loss: 1.6009 Train Accuracy: 42.46% Validation Accuracy: 50.93% Macro F1:0.4639
Epoch [44/50] Loss: 1.6366 Train Accuracy: 39.97% Validation Accuracy: 50.93% Macro F1:0.4681
Epoch [45/50] Loss: 1.6063 Train Accuracy: 38.41% Validation Accuracy: 50.31% Macro F1:0.4563
Epoch [46/50] Loss: 1.6067 Train Accuracy: 42.92% Validation Accuracy: 50.31% Macro F1:0.4592
Epoch [47/50] Loss: 1.6032 Train Accuracy: 39.81% Validation Accuracy: 51.55% Macro F1:0.4796
Epoch [48/50] Loss: 1.6059 Train Accuracy: 44.48% Validation Accuracy: 47.83% Macro F1:0.4254
Epoch [49/50] Loss: 1.6149 Train Accuracy: 38.88% Validation Accuracy: 50.93% Macro F1:0.4659
Epoch [50/50] Loss: 1.5727 Train Accuracy: 43.23% Validation Accuracy: 47.20% Macro F1:0.4128
Fold 3
Epoch [1/50] Loss: 2.3680 Train Accuracy: 12.91% Validation Accuracy: 24.22% Macro F1:0.1707
Epoch [2/50] Loss: 2.2358 Train Accuracy: 18.04% Validation Accuracy: 38.51% Macro F1:0.3038
Epoch [3/50] Loss: 2.1666 Train Accuracy: 20.68% Validation Accuracy: 32.92% Macro F1:0.2313
Epoch [4/50] Loss: 2.1274 Train Accuracy: 19.75% Validation Accuracy: 34.16% Macro F1:0.2516
Epoch [5/50] Loss: 2.0536 Train Accuracy: 24.88% Validation Accuracy: 37.89% Macro F1:0.2829
Epoch [6/50] Loss: 2.0539 Train Accuracy: 25.19% Validation Accuracy: 37.89% Macro F1:0.2862
Epoch [7/50] Loss: 1.9749 Train Accuracy: 27.06% Validation Accuracy: 37.27% Macro F1:0.2662
Epoch [8/50] Loss: 1.9766 Train Accuracy: 28.93% Validation Accuracy: 45.96% Macro F1:0.3811
Epoch [9/50] Loss: 1.9096 Train Accuracy: 30.79% Validation Accuracy: 42.86% Macro F1:0.3442
Epoch [10/50] Loss: 1.9473 Train Accuracy: 29.55% Validation Accuracy: 44.10% Macro F1:0.3638
Epoch [11/50] Loss: 1.9290 Train Accuracy: 27.84% Validation Accuracy: 40.99% Macro F1:0.3204
Epoch [12/50] Loss: 1.9009 Train Accuracy: 30.17% Validation Accuracy: 39.75% Macro F1:0.3152
Epoch [13/50] Loss: 1.9059 Train Accuracy: 30.02% Validation Accuracy: 40.99% Macro F1:0.3319
Epoch [14/50] Loss: 1.8988 Train Accuracy: 32.81% Validation Accuracy: 36.65% Macro F1:0.2777
Epoch [15/50] Loss: 1.8979 Train Accuracy: 30.95% Validation Accuracy: 42.24% Macro F1:0.3532
Epoch [16/50] Loss: 1.8723 Train Accuracy: 31.10% Validation Accuracy: 41.61% Macro F1:0.3391
Epoch [17/50] Loss: 1.8226 Train Accuracy: 34.53% Validation Accuracy: 42.24% Macro F1:0.3287
Epoch [18/50] Loss: 1.8037 Train Accuracy: 38.10% Validation Accuracy: 45.34% Macro F1:0.3628
Epoch [19/50] Loss: 1.8014 Train Accuracy: 33.59% Validation Accuracy: 43.48% Macro F1:0.3577
Epoch [20/50] Loss: 1.7561 Train Accuracy: 33.28% Validation Accuracy: 40.99% Macro F1:0.3266
Epoch [21/50] Loss: 1.7911 Train Accuracy: 34.84% Validation Accuracy: 44.72% Macro F1:0.3757
Epoch [22/50] Loss: 1.7585 Train Accuracy: 35.93% Validation Accuracy: 47.83% Macro F1:0.4078
Epoch [23/50] Loss: 1.7813 Train Accuracy: 35.15% Validation Accuracy: 39.75% Macro F1:0.3157
Epoch [24/50] Loss: 1.7244 Train Accuracy: 39.50% Validation Accuracy: 45.96% Macro F1:0.4053
Epoch [25/50] Loss: 1.7381 Train Accuracy: 32.66% Validation Accuracy: 46.58% Macro F1:0.4170
Epoch [26/50] Loss: 1.7126 Train Accuracy: 40.28% Validation Accuracy: 40.99% Macro F1:0.3366
Epoch [27/50] Loss: 1.7345 Train Accuracy: 36.70% Validation Accuracy: 47.20% Macro F1:0.4188
Epoch [28/50] Loss: 1.7089 Train Accuracy: 39.04% Validation Accuracy: 44.72% Macro F1:0.3721
Epoch [29/50] Loss: 1.7361 Train Accuracy: 38.26% Validation Accuracy: 47.83% Macro F1:0.4237
Epoch [30/50] Loss: 1.7018 Train Accuracy: 36.70% Validation Accuracy: 48.45% Macro F1:0.4224
Epoch [31/50] Loss: 1.7125 Train Accuracy: 37.95% Validation Accuracy: 46.58% Macro F1:0.4092
Epoch [32/50] Loss: 1.6866 Train Accuracy: 38.41% Validation Accuracy: 46.58% Macro F1:0.3929
Epoch [33/50] Loss: 1.6817 Train Accuracy: 40.44% Validation Accuracy: 48.45% Macro F1:0.4435
Epoch [34/50] Loss: 1.6793 Train Accuracy: 38.26% Validation Accuracy: 51.55% Macro F1:0.4735
Epoch [35/50] Loss: 1.6509 Train Accuracy: 39.04% Validation Accuracy: 49.69% Macro F1:0.4595
Epoch [36/50] Loss: 1.6815 Train Accuracy: 37.48% Validation Accuracy: 47.20% Macro F1:0.4188
Epoch [37/50] Loss: 1.6478 Train Accuracy: 38.10% Validation Accuracy: 47.83% Macro F1:0.4305
Epoch [38/50] Loss: 1.6705 Train Accuracy: 37.33% Validation Accuracy: 49.69% Macro F1:0.4546
Epoch [39/50] Loss: 1.6217 Train Accuracy: 38.72% Validation Accuracy: 45.34% Macro F1:0.3981
Epoch [40/50] Loss: 1.6264 Train Accuracy: 38.26% Validation Accuracy: 49.07% Macro F1:0.4487
Epoch [41/50] Loss: 1.6660 Train Accuracy: 40.90% Validation Accuracy: 50.93% Macro F1:0.4671
Epoch [42/50] Loss: 1.6080 Train Accuracy: 39.97% Validation Accuracy: 49.69% Macro F1:0.4570
Epoch [43/50] Loss: 1.6026 Train Accuracy: 41.21% Validation Accuracy: 51.55% Macro F1:0.4762
Epoch [44/50] Loss: 1.6142 Train Accuracy: 42.15% Validation Accuracy: 51.55% Macro F1:0.4770
Epoch [45/50] Loss: 1.6275 Train Accuracy: 40.90% Validation Accuracy: 47.20% Macro F1:0.4232
Epoch [46/50] Loss: 1.6258 Train Accuracy: 40.90% Validation Accuracy: 54.04% Macro F1:0.4952
Epoch [47/50] Loss: 1.6127 Train Accuracy: 42.77% Validation Accuracy: 52.17% Macro F1:0.4953
Epoch [48/50] Loss: 1.6154 Train Accuracy: 41.68% Validation Accuracy: 46.58% Macro F1:0.4259
Epoch [49/50] Loss: 1.6390 Train Accuracy: 38.57% Validation Accuracy: 49.69% Macro F1:0.4576
Epoch [50/50] Loss: 1.5986 Train Accuracy: 42.46% Validation Accuracy: 48.45% Macro F1:0.4489
Fold 4
Epoch [1/50] Loss: 2.3459 Train Accuracy: 11.98% Validation Accuracy: 13.04% Macro F1:0.0442
Epoch [2/50] Loss: 2.2786 Train Accuracy: 12.13% Validation Accuracy: 21.12% Macro F1:0.1115
Epoch [3/50] Loss: 2.1822 Train Accuracy: 15.86% Validation Accuracy: 35.40% Macro F1:0.2537
Epoch [4/50] Loss: 2.1606 Train Accuracy: 19.28% Validation Accuracy: 36.02% Macro F1:0.2704
Epoch [5/50] Loss: 2.0968 Train Accuracy: 23.17% Validation Accuracy: 40.37% Macro F1:0.3267
Epoch [6/50] Loss: 2.0575 Train Accuracy: 25.51% Validation Accuracy: 37.89% Macro F1:0.2819
Epoch [7/50] Loss: 2.0274 Train Accuracy: 26.44% Validation Accuracy: 34.78% Macro F1:0.2515
Epoch [8/50] Loss: 2.0084 Train Accuracy: 29.24% Validation Accuracy: 40.37% Macro F1:0.3023
Epoch [9/50] Loss: 1.9760 Train Accuracy: 29.86% Validation Accuracy: 37.27% Macro F1:0.2880
Epoch [10/50] Loss: 1.9368 Train Accuracy: 31.10% Validation Accuracy: 39.75% Macro F1:0.2982
Epoch [11/50] Loss: 1.9296 Train Accuracy: 30.17% Validation Accuracy: 40.99% Macro F1:0.3419
Epoch [12/50] Loss: 1.9092 Train Accuracy: 31.26% Validation Accuracy: 40.99% Macro F1:0.3388
Epoch [13/50] Loss: 1.8898 Train Accuracy: 29.86% Validation Accuracy: 42.24% Macro F1:0.3550
Epoch [14/50] Loss: 1.8653 Train Accuracy: 30.33% Validation Accuracy: 41.61% Macro F1:0.3531
Epoch [15/50] Loss: 1.8478 Train Accuracy: 34.06% Validation Accuracy: 42.86% Macro F1:0.3608
Epoch [16/50] Loss: 1.8413 Train Accuracy: 33.13% Validation Accuracy: 46.58% Macro F1:0.4027
Epoch [17/50] Loss: 1.8641 Train Accuracy: 32.04% Validation Accuracy: 49.69% Macro F1:0.4317
Epoch [18/50] Loss: 1.8450 Train Accuracy: 33.28% Validation Accuracy: 44.72% Macro F1:0.3693
Epoch [19/50] Loss: 1.8027 Train Accuracy: 33.28% Validation Accuracy: 44.72% Macro F1:0.3821
Epoch [20/50] Loss: 1.7685 Train Accuracy: 35.46% Validation Accuracy: 45.34% Macro F1:0.3737
Epoch [21/50] Loss: 1.8245 Train Accuracy: 33.75% Validation Accuracy: 44.72% Macro F1:0.3658
Epoch [22/50] Loss: 1.7929 Train Accuracy: 34.21% Validation Accuracy: 45.34% Macro F1:0.3883
Epoch [23/50] Loss: 1.7810 Train Accuracy: 34.21% Validation Accuracy: 45.96% Macro F1:0.3995
Epoch [24/50] Loss: 1.7611 Train Accuracy: 34.53% Validation Accuracy: 46.58% Macro F1:0.4143
Epoch [25/50] Loss: 1.7592 Train Accuracy: 33.44% Validation Accuracy: 49.69% Macro F1:0.4439
Epoch [26/50] Loss: 1.7369 Train Accuracy: 37.01% Validation Accuracy: 46.58% Macro F1:0.4056
Epoch [27/50] Loss: 1.7530 Train Accuracy: 38.26% Validation Accuracy: 48.45% Macro F1:0.4312
Epoch [28/50] Loss: 1.6918 Train Accuracy: 37.95% Validation Accuracy: 44.10% Macro F1:0.3759
Epoch [29/50] Loss: 1.7558 Train Accuracy: 36.55% Validation Accuracy: 46.58% Macro F1:0.4195
Epoch [30/50] Loss: 1.6783 Train Accuracy: 37.01% Validation Accuracy: 47.83% Macro F1:0.4124
Epoch [31/50] Loss: 1.6852 Train Accuracy: 36.39% Validation Accuracy: 46.58% Macro F1:0.3951
Epoch [32/50] Loss: 1.7117 Train Accuracy: 36.70% Validation Accuracy: 45.96% Macro F1:0.4090
Epoch [33/50] Loss: 1.7056 Train Accuracy: 38.10% Validation Accuracy: 49.69% Macro F1:0.4429
Epoch [34/50] Loss: 1.6861 Train Accuracy: 39.19% Validation Accuracy: 49.07% Macro F1:0.4445
Epoch [35/50] Loss: 1.6453 Train Accuracy: 38.26% Validation Accuracy: 48.45% Macro F1:0.4142
Epoch [36/50] Loss: 1.6389 Train Accuracy: 38.26% Validation Accuracy: 49.69% Macro F1:0.4464
Epoch [37/50] Loss: 1.6740 Train Accuracy: 39.97% Validation Accuracy: 48.45% Macro F1:0.4303
Epoch [38/50] Loss: 1.6632 Train Accuracy: 38.72% Validation Accuracy: 49.69% Macro F1:0.4389
Epoch [39/50] Loss: 1.5918 Train Accuracy: 41.84% Validation Accuracy: 50.93% Macro F1:0.4601
Epoch [40/50] Loss: 1.6738 Train Accuracy: 38.26% Validation Accuracy: 47.83% Macro F1:0.4206
Epoch [41/50] Loss: 1.6056 Train Accuracy: 42.15% Validation Accuracy: 48.45% Macro F1:0.4110
Epoch [42/50] Loss: 1.6629 Train Accuracy: 37.48% Validation Accuracy: 50.31% Macro F1:0.4561
Epoch [43/50] Loss: 1.6681 Train Accuracy: 38.10% Validation Accuracy: 48.45% Macro F1:0.4309
Epoch [44/50] Loss: 1.6594 Train Accuracy: 40.75% Validation Accuracy: 51.55% Macro F1:0.4656
Epoch [45/50] Loss: 1.6219 Train Accuracy: 40.12% Validation Accuracy: 48.45% Macro F1:0.4310
Epoch [46/50] Loss: 1.6272 Train Accuracy: 41.68% Validation Accuracy: 50.31% Macro F1:0.4506
Epoch [47/50] Loss: 1.6327 Train Accuracy: 40.59% Validation Accuracy: 49.69% Macro F1:0.4414
Epoch [48/50] Loss: 1.6598 Train Accuracy: 39.19% Validation Accuracy: 50.31% Macro F1:0.4542
Epoch [49/50] Loss: 1.5752 Train Accuracy: 39.97% Validation Accuracy: 49.07% Macro F1:0.4480
Epoch [50/50] Loss: 1.5987 Train Accuracy: 42.30% Validation Accuracy: 49.69% Macro F1:0.4387
Fold 5
Epoch [1/50] Loss: 2.3456 Train Accuracy: 11.49% Validation Accuracy: 16.25% Macro F1:0.0828
Epoch [2/50] Loss: 2.2260 Train Accuracy: 18.17% Validation Accuracy: 26.25% Macro F1:0.1433
Epoch [3/50] Loss: 2.2239 Train Accuracy: 16.93% Validation Accuracy: 30.00% Macro F1:0.1849
Epoch [4/50] Loss: 2.1447 Train Accuracy: 21.74% Validation Accuracy: 28.75% Macro F1:0.1760
Epoch [5/50] Loss: 2.1233 Train Accuracy: 22.36% Validation Accuracy: 36.88% Macro F1:0.2506
Epoch [6/50] Loss: 2.0769 Train Accuracy: 25.00% Validation Accuracy: 35.62% Macro F1:0.2424
Epoch [7/50] Loss: 2.0275 Train Accuracy: 26.71% Validation Accuracy: 40.00% Macro F1:0.3146
Epoch [8/50] Loss: 1.9602 Train Accuracy: 31.37% Validation Accuracy: 40.00% Macro F1:0.2742
Epoch [9/50] Loss: 1.9611 Train Accuracy: 31.06% Validation Accuracy: 41.25% Macro F1:0.3206
Epoch [10/50] Loss: 1.9562 Train Accuracy: 27.80% Validation Accuracy: 40.62% Macro F1:0.3188
Epoch [11/50] Loss: 1.9979 Train Accuracy: 28.73% Validation Accuracy: 40.62% Macro F1:0.3120

### 7.2 Training results
The following table summarises the best Macro F1 score achieved in each fold during five-fold cross validation. The average Macro F1 is reported as the overall training performance of the CNN model.

In [8]:
cnn_results_df = pd.DataFrame(cnn_fold_results)

print("CNN Cross Validation Results")
display(cnn_results_df)

print(f"\nAverage CNN Macro F1: {cnn_avg_f1:.4f}")

CNN Cross Validation Results

  Model  Fold  Macro F1
0   CNN     1    0.4597
1   CNN     2    0.4796
2   CNN     3    0.4953
3   CNN     4    0.4656
4   CNN     5    0.4710

Average CNN Macro F1: 0.4742

## 8 CRNN training

### 8.1 CRNN training process
The CRNN model follows the same five-fold stratified cross validation procedure as the CNN model. The convolutional layers first extract spatial features from Mel spectrograms, and the LSTM captures temporal dependencies before classification.

In [9]:
print("=" * 60)
print("CRNN Training")
print("=" * 60)

crnn_avg_f1, crnn_fold_results = cross_validation(
    train_dataset,
    CRNN
)

============================================================
CRNN Training
============================================================
Fold 1
Epoch [1/50] Loss: 2.2808 Train Accuracy: 17.88% Validation Accuracy: 25.47% Macro F1:0.1470
Epoch [2/50] Loss: 2.0717 Train Accuracy: 30.95% Validation Accuracy: 27.33% Macro F1:0.1692
Epoch [3/50] Loss: 1.9211 Train Accuracy: 31.26% Validation Accuracy: 31.06% Macro F1:0.2255
Epoch [4/50] Loss: 1.8166 Train Accuracy: 34.84% Validation Accuracy: 38.51% Macro F1:0.3275
Epoch [5/50] Loss: 1.7292 Train Accuracy: 38.41% Validation Accuracy: 35.40% Macro F1:0.2736
Epoch [6/50] Loss: 1.6985 Train Accuracy: 41.68% Validation Accuracy: 36.02% Macro F1:0.2788
Epoch [7/50] Loss: 1.7674 Train Accuracy: 35.61% Validation Accuracy: 26.09% Macro F1:0.1702
Epoch [8/50] Loss: 1.5597 Train Accuracy: 39.97% Validation Accuracy: 39.75% Macro F1:0.3000
Epoch [9/50] Loss: 1.5851 Train Accuracy: 39.66% Validation Accuracy: 43.48% Macro F1:0.3474
Epoch [10/50] Loss: 1.6816 Train Accuracy: 38.57% Validation Accuracy: 37.27% Macro F1:0.2931
Epoch [11/50] Loss: 1.9235 Train Accuracy: 30.95% Validation Accuracy: 32.30% Macro F1:0.2529
Epoch [12/50] Loss: 1.9530 Train Accuracy: 27.99% Validation Accuracy: 30.43% Macro F1:0.2202
Epoch [13/50] Loss: 1.8476 Train Accuracy: 29.24% Validation Accuracy: 35.40% Macro F1:0.3057
Epoch [14/50] Loss: 1.7364 Train Accuracy: 35.61% Validation Accuracy: 37.89% Macro F1:0.3180
Epoch [15/50] Loss: 1.6996 Train Accuracy: 39.04% Validation Accuracy: 39.13% Macro F1:0.3152
Epoch [16/50] Loss: 1.5007 Train Accuracy: 44.01% Validation Accuracy: 42.24% Macro F1:0.3551
Epoch [17/50] Loss: 1.5216 Train Accuracy: 43.39% Validation Accuracy: 43.48% Macro F1:0.3793
Epoch [18/50] Loss: 1.3809 Train Accuracy: 46.81% Validation Accuracy: 43.48% Macro F1:0.3841
Epoch [19/50] Loss: 1.4892 Train Accuracy: 45.41% Validation Accuracy: 44.10% Macro F1:0.3401
Epoch [20/50] Loss: 1.4595 Train Accuracy: 45.26% Validation Accuracy: 44.10% Macro F1:0.3640
Epoch [21/50] Loss: 1.4727 Train Accuracy: 45.72% Validation Accuracy: 44.10% Macro F1:0.4043
Epoch [22/50] Loss: 1.4380 Train Accuracy: 46.50% Validation Accuracy: 33.54% Macro F1:0.3143
Epoch [23/50] Loss: 1.6803 Train Accuracy: 41.68% Validation Accuracy: 37.89% Macro F1:0.2867
Epoch [24/50] Loss: 1.4307 Train Accuracy: 45.26% Validation Accuracy: 41.61% Macro F1:0.3540
Epoch [25/50] Loss: 1.5148 Train Accuracy: 43.23% Validation Accuracy: 41.61% Macro F1:0.3499
Epoch [26/50] Loss: 1.3878 Train Accuracy: 47.28% Validation Accuracy: 42.86% Macro F1:0.3792
Epoch [27/50] Loss: 1.4282 Train Accuracy: 49.14% Validation Accuracy: 52.80% Macro F1:0.4646
Epoch [28/50] Loss: 1.3557 Train Accuracy: 46.03% Validation Accuracy: 49.07% Macro F1:0.4504
Epoch [29/50] Loss: 1.3468 Train Accuracy: 49.92% Validation Accuracy: 49.69% Macro F1:0.4353
Epoch [30/50] Loss: 1.2766 Train Accuracy: 51.01% Validation Accuracy: 49.07% Macro F1:0.4482
Epoch [31/50] Loss: 1.2357 Train Accuracy: 51.94% Validation Accuracy: 49.07% Macro F1:0.4530
Epoch [32/50] Loss: 1.2254 Train Accuracy: 51.17% Validation Accuracy: 47.83% Macro F1:0.4427
Epoch [33/50] Loss: 1.3584 Train Accuracy: 47.90% Validation Accuracy: 50.31% Macro F1:0.4577
Epoch [34/50] Loss: 1.3046 Train Accuracy: 49.14% Validation Accuracy: 55.28% Macro F1:0.5314
Epoch [35/50] Loss: 1.3041 Train Accuracy: 52.72% Validation Accuracy: 55.90% Macro F1:0.5447
Epoch [36/50] Loss: 1.2554 Train Accuracy: 52.26% Validation Accuracy: 48.45% Macro F1:0.4534
Epoch [37/50] Loss: 1.2345 Train Accuracy: 54.28% Validation Accuracy: 52.17% Macro F1:0.4845
Epoch [38/50] Loss: 1.2858 Train Accuracy: 50.08% Validation Accuracy: 51.55% Macro F1:0.4811
Epoch [39/50] Loss: 1.1766 Train Accuracy: 54.90% Validation Accuracy: 52.80% Macro F1:0.5093
Epoch [40/50] Loss: 1.2075 Train Accuracy: 53.50% Validation Accuracy: 53.42% Macro F1:0.4936
Epoch [41/50] Loss: 1.3672 Train Accuracy: 53.50% Validation Accuracy: 43.48% Macro F1:0.3755
Epoch [42/50] Loss: 1.4843 Train Accuracy: 42.61% Validation Accuracy: 41.61% Macro F1:0.3595
Epoch [43/50] Loss: 1.5547 Train Accuracy: 44.01% Validation Accuracy: 47.83% Macro F1:0.4336
Epoch [44/50] Loss: 1.3506 Train Accuracy: 47.74% Validation Accuracy: 48.45% Macro F1:0.4201
Epoch [45/50] Loss: 1.3285 Train Accuracy: 53.34% Validation Accuracy: 46.58% Macro F1:0.4353
Epoch [46/50] Loss: 1.2798 Train Accuracy: 52.57% Validation Accuracy: 45.96% Macro F1:0.4185
Epoch [47/50] Loss: 1.3453 Train Accuracy: 45.72% Validation Accuracy: 52.17% Macro F1:0.4923
Epoch [48/50] Loss: 1.3282 Train Accuracy: 48.21% Validation Accuracy: 54.66% Macro F1:0.5198
Epoch [49/50] Loss: 1.2125 Train Accuracy: 53.19% Validation Accuracy: 52.80% Macro F1:0.4731
Epoch [50/50] Loss: 1.3763 Train Accuracy: 48.06% Validation Accuracy: 58.39% Macro F1:0.5552
Fold 2
Epoch [1/50] Loss: 2.2641 Train Accuracy: 16.02% Validation Accuracy: 28.57% Macro F1:0.1739
Epoch [2/50] Loss: 2.0743 Train Accuracy: 31.10% Validation Accuracy: 38.51% Macro F1:0.2682
Epoch [3/50] Loss: 1.7936 Train Accuracy: 37.95% Validation Accuracy: 36.02% Macro F1:0.2781
Epoch [4/50] Loss: 1.6862 Train Accuracy: 40.75% Validation Accuracy: 34.78% Macro F1:0.2816
Epoch [5/50] Loss: 1.5923 Train Accuracy: 42.46% Validation Accuracy: 42.86% Macro F1:0.3570
Epoch [6/50] Loss: 1.4705 Train Accuracy: 45.72% Validation Accuracy: 43.48% Macro F1:0.3562
Epoch [7/50] Loss: 1.6029 Train Accuracy: 41.37% Validation Accuracy: 38.51% Macro F1:0.3110
Epoch [8/50] Loss: 1.7278 Train Accuracy: 39.97% Validation Accuracy: 35.40% Macro F1:0.2645
Epoch [9/50] Loss: 1.9206 Train Accuracy: 27.53% Validation Accuracy: 38.51% Macro F1:0.2887
Epoch [10/50] Loss: 1.6815 Train Accuracy: 41.06% Validation Accuracy: 46.58% Macro F1:0.3999
Epoch [11/50] Loss: 1.4865 Train Accuracy: 44.95% Validation Accuracy: 44.10% Macro F1:0.3646
Epoch [12/50] Loss: 1.4108 Train Accuracy: 48.83% Validation Accuracy: 47.83% Macro F1:0.4080
Epoch [13/50] Loss: 1.3720 Train Accuracy: 46.66% Validation Accuracy: 50.93% Macro F1:0.4558
Epoch [14/50] Loss: 1.5255 Train Accuracy: 42.92% Validation Accuracy: 45.96% Macro F1:0.3854
Epoch [15/50] Loss: 1.3751 Train Accuracy: 48.21% Validation Accuracy: 43.48% Macro F1:0.3876
Epoch [16/50] Loss: 1.4182 Train Accuracy: 48.21% Validation Accuracy: 47.83% Macro F1:0.4483
Epoch [17/50] Loss: 1.3223 Train Accuracy: 50.08% Validation Accuracy: 45.96% Macro F1:0.4075
Epoch [18/50] Loss: 1.3163 Train Accuracy: 50.86% Validation Accuracy: 52.80% Macro F1:0.5010
Epoch [19/50] Loss: 1.3792 Train Accuracy: 50.39% Validation Accuracy: 45.96% Macro F1:0.4039
Epoch [20/50] Loss: 1.3686 Train Accuracy: 46.35% Validation Accuracy: 47.83% Macro F1:0.4103
Epoch [21/50] Loss: 1.2565 Train Accuracy: 52.57% Validation Accuracy: 54.04% Macro F1:0.5071
Epoch [22/50] Loss: 1.3542 Train Accuracy: 47.43% Validation Accuracy: 43.48% Macro F1:0.3928
Epoch [23/50] Loss: 1.2968 Train Accuracy: 51.94% Validation Accuracy: 52.17% Macro F1:0.4872
Epoch [24/50] Loss: 1.2784 Train Accuracy: 54.59% Validation Accuracy: 52.80% Macro F1:0.5122
Epoch [25/50] Loss: 1.1793 Train Accuracy: 57.23% Validation Accuracy: 49.69% Macro F1:0.4754
Epoch [26/50] Loss: 1.2279 Train Accuracy: 54.28% Validation Accuracy: 50.31% Macro F1:0.4648
Epoch [27/50] Loss: 1.2530 Train Accuracy: 53.03% Validation Accuracy: 47.83% Macro F1:0.4434
Epoch [28/50] Loss: 1.2876 Train Accuracy: 51.79% Validation Accuracy: 45.34% Macro F1:0.3907
Epoch [29/50] Loss: 1.3553 Train Accuracy: 50.39% Validation Accuracy: 48.45% Macro F1:0.4388
Epoch [30/50] Loss: 1.1913 Train Accuracy: 54.90% Validation Accuracy: 60.25% Macro F1:0.5818
Epoch [31/50] Loss: 1.2151 Train Accuracy: 55.21% Validation Accuracy: 49.07% Macro F1:0.4587
Epoch [32/50] Loss: 1.2287 Train Accuracy: 53.97% Validation Accuracy: 50.31% Macro F1:0.4515
Epoch [33/50] Loss: 1.4903 Train Accuracy: 51.01% Validation Accuracy: 47.83% Macro F1:0.4249
Epoch [34/50] Loss: 1.2767 Train Accuracy: 52.41% Validation Accuracy: 49.07% Macro F1:0.4451
Epoch [35/50] Loss: 1.2289 Train Accuracy: 56.45% Validation Accuracy: 52.17% Macro F1:0.4880
Epoch [36/50] Loss: 1.1874 Train Accuracy: 55.05% Validation Accuracy: 52.80% Macro F1:0.4809
Epoch [37/50] Loss: 1.1411 Train Accuracy: 55.83% Validation Accuracy: 56.52% Macro F1:0.5318
Epoch [38/50] Loss: 1.2041 Train Accuracy: 59.56% Validation Accuracy: 53.42% Macro F1:0.5119
Epoch [39/50] Loss: 1.1165 Train Accuracy: 57.70% Validation Accuracy: 58.39% Macro F1:0.5580
Epoch [40/50] Loss: 1.1928 Train Accuracy: 58.94% Validation Accuracy: 55.28% Macro F1:0.5209
Epoch [41/50] Loss: 1.3915 Train Accuracy: 55.21% Validation Accuracy: 41.61% Macro F1:0.3354
Epoch [42/50] Loss: 1.4922 Train Accuracy: 45.41% Validation Accuracy: 49.07% Macro F1:0.4459
Epoch [43/50] Loss: 1.2639 Train Accuracy: 51.17% Validation Accuracy: 55.28% Macro F1:0.5322
Epoch [44/50] Loss: 1.2170 Train Accuracy: 55.21% Validation Accuracy: 51.55% Macro F1:0.4791
Epoch [45/50] Loss: 1.1178 Train Accuracy: 58.01% Validation Accuracy: 52.17% Macro F1:0.4940
Epoch [46/50] Loss: 1.1864 Train Accuracy: 55.83% Validation Accuracy: 54.66% Macro F1:0.5036
Epoch [47/50] Loss: 1.0800 Train Accuracy: 60.19% Validation Accuracy: 57.76% Macro F1:0.5330
Epoch [48/50] Loss: 1.0466 Train Accuracy: 64.70% Validation Accuracy: 52.80% Macro F1:0.4772
Epoch [49/50] Loss: 1.1020 Train Accuracy: 59.41% Validation Accuracy: 57.76% Macro F1:0.5476
Epoch [50/50] Loss: 1.0391 Train Accuracy: 61.43% Validation Accuracy: 60.25% Macro F1:0.5758
Fold 3
Epoch [1/50] Loss: 2.2624 Train Accuracy: 21.15% Validation Accuracy: 23.60% Macro F1:0.1212
Epoch [2/50] Loss: 2.0558 Train Accuracy: 30.17% Validation Accuracy: 29.19% Macro F1:0.1995
Epoch [3/50] Loss: 1.8429 Train Accuracy: 35.61% Validation Accuracy: 34.78% Macro F1:0.2794
Epoch [4/50] Loss: 1.7687 Train Accuracy: 33.28% Validation Accuracy: 41.61% Macro F1:0.3547
Epoch [5/50] Loss: 1.7445 Train Accuracy: 40.12% Validation Accuracy: 40.37% Macro F1:0.3361
Epoch [6/50] Loss: 1.6919 Train Accuracy: 39.66% Validation Accuracy: 32.30% Macro F1:0.2945
Epoch [7/50] Loss: 1.5939 Train Accuracy: 42.92% Validation Accuracy: 40.99% Macro F1:0.3481
Epoch [8/50] Loss: 1.5911 Train Accuracy: 42.46% Validation Accuracy: 38.51% Macro F1:0.3230
Epoch [9/50] Loss: 1.5539 Train Accuracy: 43.08% Validation Accuracy: 36.02% Macro F1:0.3213
Epoch [10/50] Loss: 1.8045 Train Accuracy: 33.59% Validation Accuracy: 34.16% Macro F1:0.2651
Epoch [11/50] Loss: 1.7477 Train Accuracy: 35.93% Validation Accuracy: 35.40% Macro F1:0.2772
Epoch [12/50] Loss: 1.6164 Train Accuracy: 42.15% Validation Accuracy: 44.72% Macro F1:0.3861
Epoch [13/50] Loss: 1.4960 Train Accuracy: 43.08% Validation Accuracy: 44.72% Macro F1:0.4209
Epoch [14/50] Loss: 1.4518 Train Accuracy: 48.37% Validation Accuracy: 44.10% Macro F1:0.4000
Epoch [15/50] Loss: 1.3991 Train Accuracy: 50.08% Validation Accuracy: 46.58% Macro F1:0.4340
Epoch [16/50] Loss: 1.4391 Train Accuracy: 46.35% Validation Accuracy: 43.48% Macro F1:0.4071
Epoch [17/50] Loss: 1.4419 Train Accuracy: 44.95% Validation Accuracy: 45.34% Macro F1:0.4374
Epoch [18/50] Loss: 1.8054 Train Accuracy: 34.99% Validation Accuracy: 29.19% Macro F1:0.2366
Epoch [19/50] Loss: 1.5778 Train Accuracy: 40.75% Validation Accuracy: 38.51% Macro F1:0.3114
Epoch [20/50] Loss: 1.4660 Train Accuracy: 45.57% Validation Accuracy: 42.86% Macro F1:0.3818
Epoch [21/50] Loss: 1.3813 Train Accuracy: 48.21% Validation Accuracy: 40.99% Macro F1:0.3521
Epoch [22/50] Loss: 1.4543 Train Accuracy: 44.32% Validation Accuracy: 44.72% Macro F1:0.4183
Epoch [23/50] Loss: 1.3466 Train Accuracy: 48.52% Validation Accuracy: 44.10% Macro F1:0.4051
Epoch [24/50] Loss: 1.3992 Train Accuracy: 47.43% Validation Accuracy: 41.61% Macro F1:0.3445
Epoch [25/50] Loss: 1.3578 Train Accuracy: 46.35% Validation Accuracy: 42.86% Macro F1:0.3997
Epoch [26/50] Loss: 1.3973 Train Accuracy: 46.19% Validation Accuracy: 44.72% Macro F1:0.3987
Epoch [27/50] Loss: 1.2750 Train Accuracy: 50.08% Validation Accuracy: 45.96% Macro F1:0.4206
Epoch [28/50] Loss: 1.3222 Train Accuracy: 48.21% Validation Accuracy: 45.34% Macro F1:0.4294
Epoch [29/50] Loss: 1.2492 Train Accuracy: 53.50% Validation Accuracy: 44.10% Macro F1:0.4150
Epoch [30/50] Loss: 1.3790 Train Accuracy: 48.06% Validation Accuracy: 31.68% Macro F1:0.2556
Epoch [31/50] Loss: 1.6226 Train Accuracy: 39.97% Validation Accuracy: 35.40% Macro F1:0.3218
Epoch [32/50] Loss: 1.4110 Train Accuracy: 45.72% Validation Accuracy: 44.72% Macro F1:0.3899
Epoch [33/50] Loss: 1.5374 Train Accuracy: 42.46% Validation Accuracy: 40.37% Macro F1:0.3656
Epoch [34/50] Loss: 1.3611 Train Accuracy: 47.74% Validation Accuracy: 49.69% Macro F1:0.4471
Epoch [35/50] Loss: 1.3129 Train Accuracy: 52.72% Validation Accuracy: 47.20% Macro F1:0.4458
Epoch [36/50] Loss: 1.3872 Train Accuracy: 48.68% Validation Accuracy: 44.72% Macro F1:0.4451
Epoch [37/50] Loss: 1.2964 Train Accuracy: 51.48% Validation Accuracy: 50.31% Macro F1:0.4795
Epoch [38/50] Loss: 1.3266 Train Accuracy: 49.77% Validation Accuracy: 47.83% Macro F1:0.4477
Epoch [39/50] Loss: 1.4262 Train Accuracy: 47.90% Validation Accuracy: 49.07% Macro F1:0.4628
Epoch [40/50] Loss: 1.2872 Train Accuracy: 50.86% Validation Accuracy: 47.83% Macro F1:0.4425
Epoch [41/50] Loss: 1.2919 Train Accuracy: 50.23% Validation Accuracy: 52.17% Macro F1:0.4986
Epoch [42/50] Loss: 1.3006 Train Accuracy: 52.26% Validation Accuracy: 49.07% Macro F1:0.4681
Epoch [43/50] Loss: 1.2785 Train Accuracy: 52.10% Validation Accuracy: 52.80% Macro F1:0.5006
Epoch [44/50] Loss: 1.0771 Train Accuracy: 56.30% Validation Accuracy: 50.31% Macro F1:0.4750
Epoch [45/50] Loss: 1.1451 Train Accuracy: 55.68% Validation Accuracy: 49.69% Macro F1:0.4895
Epoch [46/50] Loss: 1.1828 Train Accuracy: 55.05% Validation Accuracy: 53.42% Macro F1:0.4992
Epoch [47/50] Loss: 1.0958 Train Accuracy: 58.01% Validation Accuracy: 49.69% Macro F1:0.4896
Epoch [48/50] Loss: 1.2405 Train Accuracy: 50.54% Validation Accuracy: 47.83% Macro F1:0.4688
Epoch [49/50] Loss: 1.2102 Train Accuracy: 54.74% Validation Accuracy: 52.80% Macro F1:0.5103
Epoch [50/50] Loss: 1.1489 Train Accuracy: 57.70% Validation Accuracy: 47.83% Macro F1:0.4381
Fold 4
Epoch [1/50] Loss: 2.2532 Train Accuracy: 17.26% Validation Accuracy: 25.47% Macro F1:0.1281
Epoch [2/50] Loss: 2.0084 Train Accuracy: 30.64% Validation Accuracy: 31.68% Macro F1:0.1945
Epoch [3/50] Loss: 1.8336 Train Accuracy: 35.46% Validation Accuracy: 32.30% Macro F1:0.2388
Epoch [4/50] Loss: 1.7399 Train Accuracy: 38.72% Validation Accuracy: 29.81% Macro F1:0.2061
Epoch [5/50] Loss: 1.8001 Train Accuracy: 34.68% Validation Accuracy: 38.51% Macro F1:0.2934
Epoch [6/50] Loss: 1.6697 Train Accuracy: 36.86% Validation Accuracy: 39.13% Macro F1:0.3136
Epoch [7/50] Loss: 1.5736 Train Accuracy: 42.15% Validation Accuracy: 37.27% Macro F1:0.2768
Epoch [8/50] Loss: 1.5953 Train Accuracy: 37.95% Validation Accuracy: 39.13% Macro F1:0.3313
Epoch [9/50] Loss: 1.5424 Train Accuracy: 42.61% Validation Accuracy: 41.61% Macro F1:0.3741
Epoch [10/50] Loss: 1.5263 Train Accuracy: 40.90% Validation Accuracy: 47.83% Macro F1:0.4369
Epoch [11/50] Loss: 1.4019 Train Accuracy: 48.52% Validation Accuracy: 51.55% Macro F1:0.4855
Epoch [12/50] Loss: 1.4344 Train Accuracy: 46.50% Validation Accuracy: 44.72% Macro F1:0.3808
Epoch [13/50] Loss: 1.5762 Train Accuracy: 36.24% Validation Accuracy: 45.34% Macro F1:0.4036
Epoch [14/50] Loss: 1.5336 Train Accuracy: 42.15% Validation Accuracy: 43.48% Macro F1:0.3675
Epoch [15/50] Loss: 1.4320 Train Accuracy: 47.59% Validation Accuracy: 49.07% Macro F1:0.4678
Epoch [16/50] Loss: 1.3730 Train Accuracy: 49.14% Validation Accuracy: 45.34% Macro F1:0.4085
Epoch [17/50] Loss: 1.3822 Train Accuracy: 47.74% Validation Accuracy: 44.72% Macro F1:0.3943
Epoch [18/50] Loss: 1.4941 Train Accuracy: 44.79% Validation Accuracy: 38.51% Macro F1:0.3206
Epoch [19/50] Loss: 1.3839 Train Accuracy: 48.52% Validation Accuracy: 39.13% Macro F1:0.3498
Epoch [20/50] Loss: 1.3286 Train Accuracy: 47.59% Validation Accuracy: 49.07% Macro F1:0.4943
Epoch [21/50] Loss: 1.2381 Train Accuracy: 50.70% Validation Accuracy: 52.17% Macro F1:0.5004
Epoch [22/50] Loss: 1.2869 Train Accuracy: 50.86% Validation Accuracy: 48.45% Macro F1:0.4710
Epoch [23/50] Loss: 1.2468 Train Accuracy: 53.19% Validation Accuracy: 47.83% Macro F1:0.4392
Epoch [24/50] Loss: 1.3092 Train Accuracy: 49.61% Validation Accuracy: 49.69% Macro F1:0.4654
Epoch [25/50] Loss: 1.3275 Train Accuracy: 48.83% Validation Accuracy: 52.80% Macro F1:0.5094
Epoch [26/50] Loss: 1.3933 Train Accuracy: 51.32% Validation Accuracy: 49.07% Macro F1:0.4477
Epoch [27/50] Loss: 1.2983 Train Accuracy: 51.94% Validation Accuracy: 46.58% Macro F1:0.4287
Epoch [28/50] Loss: 1.2810 Train Accuracy: 52.10% Validation Accuracy: 52.80% Macro F1:0.4947
Epoch [29/50] Loss: 1.5194 Train Accuracy: 44.63% Validation Accuracy: 32.92% Macro F1:0.2711
Epoch [30/50] Loss: 1.5840 Train Accuracy: 37.79% Validation Accuracy: 42.86% Macro F1:0.3530
Epoch [31/50] Loss: 1.3709 Train Accuracy: 47.90% Validation Accuracy: 47.20% Macro F1:0.4333
Epoch [32/50] Loss: 1.9548 Train Accuracy: 29.39% Validation Accuracy: 31.06% Macro F1:0.2377
Epoch [33/50] Loss: 1.7468 Train Accuracy: 32.66% Validation Accuracy: 47.83% Macro F1:0.4069
Epoch [34/50] Loss: 1.5229 Train Accuracy: 43.23% Validation Accuracy: 45.34% Macro F1:0.3967
Epoch [35/50] Loss: 1.3375 Train Accuracy: 48.21% Validation Accuracy: 46.58% Macro F1:0.4222
Epoch [36/50] Loss: 1.3099 Train Accuracy: 48.68% Validation Accuracy: 50.93% Macro F1:0.4733
Epoch [37/50] Loss: 1.3175 Train Accuracy: 52.10% Validation Accuracy: 59.01% Macro F1:0.5573
Epoch [38/50] Loss: 1.3228 Train Accuracy: 51.32% Validation Accuracy: 43.48% Macro F1:0.3843
Epoch [39/50] Loss: 1.2239 Train Accuracy: 54.59% Validation Accuracy: 53.42% Macro F1:0.4980
Epoch [40/50] Loss: 1.1965 Train Accuracy: 55.37% Validation Accuracy: 52.80% Macro F1:0.4915
Epoch [41/50] Loss: 1.1933 Train Accuracy: 52.88% Validation Accuracy: 56.52% Macro F1:0.5445
Epoch [42/50] Loss: 1.1452 Train Accuracy: 53.97% Validation Accuracy: 54.04% Macro F1:0.5028
Epoch [43/50] Loss: 1.0559 Train Accuracy: 59.72% Validation Accuracy: 55.28% Macro F1:0.5273
Epoch [44/50] Loss: 1.1167 Train Accuracy: 57.85% Validation Accuracy: 48.45% Macro F1:0.4353
Epoch [45/50] Loss: 1.2568 Train Accuracy: 54.59% Validation Accuracy: 57.14% Macro F1:0.5525
Epoch [46/50] Loss: 1.1047 Train Accuracy: 60.34% Validation Accuracy: 54.04% Macro F1:0.4858
Epoch [47/50] Loss: 1.1285 Train Accuracy: 57.85% Validation Accuracy: 57.14% Macro F1:0.5481
Epoch [48/50] Loss: 1.1261 Train Accuracy: 60.50% Validation Accuracy: 58.39% Macro F1:0.5738
Epoch [49/50] Loss: 1.0731 Train Accuracy: 57.85% Validation Accuracy: 57.14% Macro F1:0.5393
Epoch [50/50] Loss: 1.1760 Train Accuracy: 55.99% Validation Accuracy: 40.99% Macro F1:0.3697
Fold 5
Epoch [1/50] Loss: 2.2702 Train Accuracy: 14.29% Validation Accuracy: 24.38% Macro F1:0.1516
Epoch [2/50] Loss: 2.0935 Train Accuracy: 27.95% Validation Accuracy: 39.38% Macro F1:0.3061
Epoch [3/50] Loss: 1.9296 Train Accuracy: 33.23% Validation Accuracy: 33.75% Macro F1:0.2413
Epoch [4/50] Loss: 1.7346 Train Accuracy: 38.20% Validation Accuracy: 38.75% Macro F1:0.3087
Epoch [5/50] Loss: 1.8537 Train Accuracy: 32.76% Validation Accuracy: 30.62% Macro F1:0.2466
Epoch [6/50] Loss: 1.7605 Train Accuracy: 35.40% Validation Accuracy: 36.88% Macro F1:0.2781
Epoch [7/50] Loss: 1.6202 Train Accuracy: 39.91% Validation Accuracy: 40.00% Macro F1:0.3271
Epoch [8/50] Loss: 1.5844 Train Accuracy: 41.30% Validation Accuracy: 39.38% Macro F1:0.3120
Epoch [9/50] Loss: 1.7735 Train Accuracy: 35.56% Validation Accuracy: 41.88% Macro F1:0.3513
Epoch [10/50] Loss: 1.6976 Train Accuracy: 36.49% Validation Accuracy: 41.25% Macro F1:0.3308
Epoch [11/50] Loss: 1.6932 Train Accuracy: 36.49% Validation Accuracy: 38.75% Macro F1:0.3279

### 8.2 CRNN training results
The best Macro F1 score from each fold is summarised below. The average Macro F1 is used as the overall performance indicator of the CRNN model.

In [10]:
crnn_results_df = pd.DataFrame(crnn_fold_results)

print("CRNN Cross Validation Results")
display(crnn_results_df)

print(f"\nAverage CRNN Macro F1: {crnn_avg_f1:.4f}")

CRNN Cross Validation Results

  Model  Fold  Macro F1
0  CRNN     1    0.5552
1  CRNN     2    0.5818
2  CRNN     3    0.5103
3  CRNN     4    0.5738
4  CRNN     5    0.5591

Average CRNN Macro F1: 0.5560